// src/LanguageContext.jsx
import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
  th: {
    // Sidebar & Navigation
    homepage: "หน้าแรก",
    product: "สินค้า",
    calculate: "คำนวณ",
    conclusion: "สรุปผล",
    contact: "ติดต่อเรา",
    creator_panel: "แผงควบคุมร้านค้า",
    event_booth: "อีเวนต์บูธ",
    login: "เข้าสู่ระบบ",
    cart: "รถเข็น",
    search: "ค้นหาสินค้า",
    switch_lang: "🇺🇸 Switch to English",
    calculate_title: "คำนวณราคาสินค้า",
    sales_history: "ประวัติการขาย",
    all_creators: "🌟 รวมทั้งหมด",
    artist: "นักวาด",
    click_to_options: "▶ คลิกเพื่อเลือกตัวเลือก",
    stock_remaining: "คงเหลือ",
    total_amount: "ยอดรวม",
    payment_transfer: "โอนเงิน",
    payment_cash: "เงินสด",
    confirm_transaction: "ยืนยันการทำรายการ?",
    pay_via: "ชำระผ่าน",
    cancel: "ยกเลิก",
    confirm: "ยืนยัน",
    loading_data: "กำลังโหลดข้อมูล...",
    success_checkout: "บันทึกการขายและตัดสต็อกเรียบร้อย!",
    error_checkout: "เกิดข้อผิดพลาดในการทำรายการ",
    back_to_sell: "◀ กลับไปหน้าขาย",
    history_title: "ประวัติการขาย",
    loading_history: "กำลังโหลดข้อมูลประวัติ...",
    no_history: "ยังไม่มีประวัติการขาย",
    time: "เวลา",
    delete: "ลบ",
    pay_via_label: "💳 ชำระผ่าน",
    confirm_delete_title: "ยืนยันการลบ?",
    confirm_delete_msg: "คุณต้องการลบรายการนี้ใช่หรือไม่?",
    all_order: "ทั้งออเดอร์",
    delete_all_order: "❌ ลบออเดอร์ทั้งหมด",
    cancel_btn: "ยกเลิก",
    confirm_delete_btn: "ยืนยันลบ",
    error_delete: "เกิดข้อผิดพลาดในการลบข้อมูล",
    select_options_sub: "กรุณาเลือกตัวเลือกสินค้าที่ต้องการ",
    no_image: "ไม่มีรูปภาพ",
    confirm_selection: "ยืนยันการเลือก",
    stock_alert: "สินค้านี้เหลือสต็อกเพียง",
    unit: "ชิ้น",
    processing: "กำลังประมวลผลข้อมูล...",
    all_summary: "🌟 รวมทั้งหมด",
    choose_date: "เลือกวันที่",
    total_revenue: "รายได้ทั้งหมด",
    baht: "บาท",
    best_seller_title: "สินค้าขายดี",
    total_price: "ราคารวม",
    total_qty: "จำนวนรวม",
    product_type: "ประเภทของสินค้า",
    out_of_stock_title: "สินค้าที่หมดสต็อก",
    no_stock_issues: "- ไม่มีสินค้าหมด -",
    daily_report_title: "รายงานการขายประจำวัน",
    no_sales_data: "ยังไม่มีข้อมูลการขายสำหรับนักวาดท่านนี้",
    table_date: "วันที่",
    table_name: "ชื่อ",
    table_product: "สินค้า",
    table_price: "ราคา",
    table_option: "ตัวเลือก",
    table_stock: "สต็อก",
    table_quantity: "จำนวน",
    table_total: "รวม",
    contact_title: "ติดต่อเรา",
    report_problem: "แจ้งปัญหาการใช้งาน :",
    suggestion: "ข้อเสนอแนะ :",
    inventory_title: "จัดการสินค้า (Inventory)",
    inventory_subtitle: "สินค้าทั้งหมดของ",
    add_new_product: "เพิ่มสินค้าใหม่",
    loading_products: "กำลังโหลดข้อมูลสินค้า...",
    no_products: "คุณยังไม่มีสินค้าในระบบ",
    no_category: "ไม่ได้ระบุหมวดหมู่",
    table_variation: "ตัวเลือก",
    table_actions: "จัดการ",
    edit_button: "แก้ไข (Edit)",
    delete_button: "ลบ (Delete)",
    confirm_delete_title: "ยืนยันการลบ?",
    confirm_delete_msg: "คุณต้องการลบรายการนี้ใช่หรือไม่?",
    confirm_delete_button: "ยืนยันลบ",
    cancel_button: "ยกเลิก",
    delete_error: "ไม่สามารถลบข้อมูลได้",
    table_product: "สินค้า",
    table_option: "ออปชัน",
    table_price: "ราคา",
    table_stock: "สต็อก",
    loading_booth: "กำลังโหลดข้อมูลบูธของคุณ...",
    booth_not_found: "ไม่พบข้อมูลบูธของคุณในระบบ",
    booth_not_found_desc: "ชื่อผู้ใช้ อาจยังไม่มีบูธที่ผูกไว้ในระบบ",
    edit_booth_info: "แก้ไขข้อมูลบูธ",
    save_booth_success: "บันทึกข้อมูลหน้าร้านเรียบร้อยแล้ว!",
    save_error: "เกิดข้อผิดพลาดในการบันทึกข้อมูล",
    saving: "กำลังบันทึก...",
    save_button: "บันทึกข้อมูล",
    cancel_button: "ยกเลิก",
    placeholder_cover_url: "วางลิงก์รูปหน้าปกใหม่ที่นี่...",
    placeholder_description: "กรอกคำอธิบายบูธของคุณ...",
    your_booth_badge: "บูธของคุณ",
    no_description: "ยังไม่มีคำอธิบายบูธ",
    booth_number_label: "หมายเลขบูธ",
    products_in_booth: "สินค้าในบูธ",
    items_unit: "รายการ",
    remaining: "เหลือ",
    creator_all: "รวมทั้งหมด",
    no_products_by: "ไม่มีสินค้าของ",
    in_this_booth: "ในบูธนี้",
    login: "เข้าสู่ระบบ",
    signup: "สมัครสมาชิก",
    logout: "ออกจากระบบ",
    creator_mode: "โหมดนักวาด",
    buyer_mode: "ผู้ซื้อ",
    remember_me: "จดจำฉันไว้",
    no_account_yet: "ยังไม่มีบัญชีใช่ไหม?",
    email_not_found: "ไม่พบอีเมลนี้ในระบบ โปรดตรวจสอบอีกครั้ง",
    db_error: "เกิดข้อผิดพลาดในการเชื่อมต่อฐานข้อมูล",
    cart: "ตะกร้าสินค้า",
    history: "ประวัติการสั่งซื้อ",
    cart_empty: "ไม่มีสินค้าในตะกร้า",
    select_all: "เลือกทั้งหมด",
    table_product: "สินค้า",
    table_type: "ประเภท",
    table_price: "ราคารวม",
    action_delete: "ลบออก",
    action_cancel: "ยกเลิก",
    total: "ยอดรวมทั้งหมด",
    unit: "ชิ้น",
    loading: "กำลังโหลด...",
    landing_subtitle: "คอมมูนิตี้ตลาดนัดสำหรับสายอาร์ต",
    buyer_login: "เข้าสู่ระบบผู้ซื้อ",
    creator_zone: "เข้าสู่ระบบศิลปิน (Creator)",
    guest_view: "เข้าชมในฐานะบุคคลทั่วไป",
    or: "หรือ"
  },
  en: {
    homepage: "Homepage",
    product: "Product",
    calculate: "Calculate",
    conclusion: "Conclusion",
    contact: "Contact us",
    creator_panel: "Creator Panel",
    event_booth: "Event Booth",
    login: "Login",
    cart: "Cart",
    search: "Search",
    switch_lang: "🇹🇭 เปลี่ยนเป็นภาษาไทย",
    calculate_title: "Calculate total price",
    sales_history: "Sales History",
    all_creators: "🌟 All Creators",
    artist: "Artist",
    click_to_options: "▶ Click to select options",
    stock_remaining: "Stock",
    total_amount: "Total",
    payment_transfer: "Transfer",
    payment_cash: "Cash",
    confirm_transaction: "Confirm Transaction?",
    pay_via: "Pay via",
    cancel: "Cancel",
    confirm: "Confirm",
    loading_data: "Loading data...",
    success_checkout: "Sales recorded and stock updated!",
    error_checkout: "An error occurred during transaction",
    back_to_sell: "◀ Back to Sales",
    history_title: "Sales History",
    loading_history: "Loading history...",
    no_history: "No sales history found",
    time: "Time",
    delete: "Delete",
    pay_via_label: "💳 Paid via",
    confirm_delete_title: "Confirm Delete?",
    confirm_delete_msg: "Are you sure you want to delete this item?",
    all_order: "Entire Order",
    delete_all_order: "❌ Delete entire order",
    cancel_btn: "Cancel",
    confirm_delete_btn: "Confirm Delete",
    error_delete: "An error occurred while deleting",
    select_options_sub: "Please select your preferred options",
    no_image: "No Image",
    confirm_selection: "Confirm Selection",
    stock_alert: "This item only has",
    unit: "items left",
    processing: "Processing data...",
    all_summary: "🌟 All Summary",
    choose_date: "Choose Date",
    total_revenue: "Total Revenue",
    baht: "Baht",
    best_seller_title: "Best Seller",
    total_price: "Total Price",
    total_qty: "Total Quantity",
    product_type: "Product Type",
    out_of_stock_title: "Out of Stock Products",
    no_stock_issues: "- No stock issues -",
    daily_report_title: "Daily Sales Report",
    no_sales_data: "No sales data for this creator",
    table_date: "Date",
    table_name: "Name",
    table_product: "Product",
    table_price: "Price",
    table_option: "Option",
    table_stock: "Stock",
    table_quantity: "Qty",
    table_total: "Total",
    contact_title: "Contact",
    report_problem: "Report a Problem :",
    suggestion: "Suggestion :",
    inventory_title: "Inventory Management",
    inventory_subtitle: "All products of",
    add_new_product: "Add New Product",
    loading_products: "Loading products...",
    no_products: "No products in system",
    no_category: "Uncategorized",
    table_variation: "Variation",
    table_actions: "Actions",
    edit_button: "Edit",
    delete_button: "Delete",
    confirm_delete_title: "Confirm Delete?",
    confirm_delete_msg: "Are you sure you want to delete this item?",
    confirm_delete_button: "Confirm",
    cancel_button: "Cancel",
    delete_error: "Could not delete data",
    table_product: "Product",
    table_option: "Option",
    table_price: "Price",
    table_stock: "Stock",
    loading_booth: "Loading your booth data...",
    booth_not_found: "Booth information not found",
    booth_not_found_desc: "The username might not have a linked booth in the system",
    edit_booth_info: "Edit Booth Info",
    save_booth_success: "Booth information saved successfully!",
    save_error: "An error occurred while saving",
    saving: "Saving...",
    save_button: "Save Data",
    cancel_button: "Cancel",
    placeholder_cover_url: "Paste new cover image URL here...",
    placeholder_description: "Enter your booth description...",
    your_booth_badge: "YOUR BOOTH",
    no_description: "No description available",
    booth_number_label: "Booth Number",
    products_in_booth: "Products in Booth",
    items_unit: "items",
    remaining: "Remaining",
    creator_all: "All Items",
    no_products_by: "No products by",
    in_this_booth: "in this booth",
    login: "Login",
    signup: "Sign-up",
    logout: "Logout",
    creator_mode: "Creator Mode",
    buyer_mode: "Buyer",
    no_account_yet: "Don't have an account yet?",
    email_not_found: "Email not found. Please try again.",
    db_error: "Database connection error.",
    cart: "Shopping Cart",
    history: "Order History",
    cart_empty: "Your cart is empty",
    select_all: "Select All",
    table_product: "Product",
    table_type: "Type",
    table_price: "Total Price",
    action_delete: "Delete",
    action_cancel: "Cancel",
    total: "Grand Total",
    unit: "pcs",
    loading: "Loading...",
    buyer_login: "Buyer Login",
    creator_zone: "Creator Zone",
    guest_view: "Guest View",
    or: "OR",
    landing_subtitle: "Your creative marketplace community"
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('th');
  const t = (key) => translations[lang][key] || key;
  const toggleLang = () => setLang(prev => (prev === 'th' ? 'en' : 'th'));

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);